id: P5A5AF356
initial_creation_type: ocr
source_metadata:
  volumes:
    e66e80f3cdc045f0859f9aea84821665:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: འཕགས་པ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་ཅན་གྱི་སྒྲུབ་ཐབས་ཀྱི་མན་ངག་རྒྱ་ཆེར་བཤད་པའི་འགྲེལ་པ།
      total_pages: 1853
      volume_number: 25
